server:
  port: 7000
spring:
  application:
    name: CoreService
  cloud:
    close-feign:
      #负载均衡配置 [随机random - 轮询roundRobin]
      balancer: roundRobin
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
