server:
  port: 5000
spring:
  application:
    name: customer
  cloud:
    close-feign:
      balancer: random
    zookeeper:
      connect-string: 127.0.0.1:2181
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848