server:
  port: 4000
spring:
  application:
    name: test
  cloud:
    close-feign:
      #负载均衡配置 [随机random - 轮询roundRobin]
      balancer: roundRobin
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
