server:
  port: 4000
spring:
  application:
    name: UserService
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:4000/eurka
